CREATE TABLE IF NOT EXISTS person (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    home_address VARCHAR(500),
    education VARCHAR(255) NOT NULL,
    status BOOLEAN NOT NULL,
    desired_position VARCHAR(255),
    desired_salary NUMERIC(12, 2)
);

CREATE TABLE IF NOT EXISTS company (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE IF NOT EXISTS vacancy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    position VARCHAR(255) NOT NULL,
    salary NUMERIC(12, 2) NOT NULL,
    required_education VARCHAR(255),
    requirements TEXT,
    status BOOLEAN NOT NULL,
    CONSTRAINT fk_vacancy_company
        FOREIGN KEY (company_id) REFERENCES company (id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS work_experience (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    position VARCHAR(255) NOT NULL,
    salary NUMERIC(12, 2) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE,
    CONSTRAINT fk_work_experience_person
        FOREIGN KEY (person_id) REFERENCES person (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_work_experience_company
        FOREIGN KEY (company_id) REFERENCES company (id)
);
